### ISSUE TITLE
Does Angel have stream response?

### ISSUE THREAD

**Issue by BLeAm** [angel-dart/angel#104]
I'm looking for a way to stream data via Angel's ResponseContext with no luck, I've looked through the document, the closest thing I've found is streamFile but if the data I want to response don't come from files, what approach am I supposed to do?

**Comment by thosakwe** [comment]
`ResponseContext` implements both `StreamSink<List<int>>` and `StringSink`:
https://github.com/angel-dart/framework/blob/master/lib/src/core/response_context.dart#L20-L21

Thus, you can pipe streams, etc.

By default, responses are streamed directly to the underlying object. So in the HTTP context, data is written directly to the underlying `HttpResponse`.

Buffering can be enabled by calling `ResponseContext.useBuffer`.

**Comment by BLeAm** [comment]
Thank you. :)
