### ISSUE TITLE
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 3000

### ISSUE THREAD

**Issue by jhyvictory** [angel-dart/angel#105]
when i tried to run the example code, i faced the below exception, why?

SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 3000
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:591:7)
<asynchronous suspension>
#1      _RawServerSocket.bind (dart:io-patch/socket_patch.dart:1206:26)
#2      _ServerSocket.bind (dart:io-patch/socket_patch.dart:1466:29)
#3      ServerSocket.bind (dart:io-patch/socket_patch.dart:1457:26)
#4      _HttpServer.bind (dart:_http/http_impl.dart:2520:25)
#5      HttpServer.bind (dart:_http:227:19)
#6      Driver.generateServer (package:angel_framework/src/core/driver.dart:38:7)
#7      Driver.startServer (package:angel_framework/src/core/driver.dart:43:12)
#8      main (file:///D:/workspace/hangel/bin/main.dart:7:16)
<asynchronous suspension>
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

**Comment by thosakwe** [comment]
Can you bind any socket at port 3000 at all? You might just already have something else listening there. Try running `nc -lk 3000` and see what happens.

Closing, as this isn't an Angel-specific issue.
