### ISSUE TITLE
Does angel have interceptors like redstone?

### ISSUE THREAD

**Issue by ejabu** [angel-dart/angel#113]
I am now considering dart as my backend. Does angel have similiar mechanism to intercept like redstone below ?

![image](https://user-images.githubusercontent.com/2019630/59844097-3b37f580-9384-11e9-805c-75fc36f992e0.png)
[reference](http://redstonedart.org/)

If already built, can I look to the documentation, since I cannot found using keyword 'interceptors' before

best regards

**Comment by thosakwe** [comment]
Angel has had this since day one; however, the name "middleware" is used, instead of "interceptor."
https://docs.angel-dart.dev/guides/middleware
