### ISSUE TITLE
Controller and Service

### ISSUE THREAD

**Issue by carmas123** [angel-dart/angel#117]
In a REST Api server what is the real difference from controllers and services?

**Comment by thosakwe** [comment]
* Controllers: dependency injection-enabled classes that allow you to group and share common functionality among routes
* Services: an abstraction over CRUD/create-read-update-delete, and implement a very specific API. These exist to make building CRUD API's extremely simple, as you no longer have to write route handlers, instead writing just hooks.

https://docs.angel-dart.dev/guides/controllers
https://docs.angel-dart.dev/guides/service-basics
