### ISSUE TITLE
Setting up on Google cloud with Docker

### ISSUE THREAD

**Issue by arrrrny** [angel-dart/angel#124]
Hi, 

When I run angel on my mac using docker, if I set the server address to 172.17.0.2:8080 it works fine.(Docker's local IP)  However, when I deploy it to google cloud I get below error. I set the address to the application endpoint(lucky-altar-256810.appspot.com). My previous deploy without angel just launched fine. 
Neither below worked:
await http.startServer('localhost', 8080);
await http.startServer('lucky-altar-256810.appspot.com', 8080);

Any idea?

Another thing is, I want to use Scheduled tasks but it seems like https://github.com/angel-dart/task removed from pub. 

ERROR: (gcloud.app.deploy) Error Response: [9] 
Application startup error:
Observatory listening on http://0.0.0.0:8181/N1XLzae_88E=/
Unhandled exception:
SocketException: Failed to create server socket (OS Error: Cannot assign requested address, errno = 99), address = lucky-altar-256810.appspot.com, port = 8080
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:642:7)
<asynchronous suspension>
#1      _RawServerSocket.bind (dart:io-patch/socket_patch.dart:1260:26)
#2      _ServerSocket.bind (dart:io-patch/socket_patch.dart:1520:29)
#3      ServerSocket.bind (dart:io-patch/socket_patch.dart:1511:26)
#4      _HttpServer.bind (dart:_http/http_impl.dart:2594:25)
#5      HttpServer.bind (dart:_http:227:19)
#6      Driver.generateServer (package:angel_framework/src/core/driver.dart:38:7)
#7      Driver.startServer (package:angel_framework/src/core/driver.dart:43:12)
#8      main (file:///app/bin/server.dart:17:14)
<asynchronous suspension>
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by thosakwe** [comment]
As you can see, that’s not actually an Angel issue - it ultimately comes down to whether you can bind a socket at the given host. Maybe the appspot URL doesn’t resolve directly to the given IP.

Also, the task package wasn’t removed. It wasn’t updated for Dart 2, so it won’t appear on Pub search. In reality, though, I recommend `package:cron`. The old `angel_task` package was heavily reliant on mirrors.

**Comment by arrrrny** [comment]
I am first time using docker, I found this https://github.com/angel-dart/angel/blob/master/Dockerfile
Have you tried running this on Google cloud? How do you bind server address?

**Comment by thosakwe** [comment]
I am neither a Google Cloud customer, nor a Docker user. The Dockerfile is just there to get you started, and will likely need tweaking per-project.

**Comment by thosakwe** [comment]
I would recommend just doing what works, which is passing the server’s IP, OR `0.0.0.0`.

**Comment by arrrrny** [comment]
Tried both, didn't work :/ When I passed the server IP got the same error, When I used 0.0.0.0 or localhost, deployed without issue but I got 502 Bad Gateway.

**Comment by thosakwe** [comment]
I'm not sure what the underlying issue, but I can tell you for sure it's not Angel-related. You might want to consult Google Cloud support.

**Comment by arrrrny** [comment]
I got this up and running. In case other need to run on google cloud platform, here are the instructions:

First and foremost, I switch to Google cloud run instead of Google app engine, it is faster and way cheaper:
I highly recommend creating angel project using CLI. This prepares everything **production-ready** and does all the boilerplate. 
1: pub global activate angel_cli
2: angel init app_name
3:Choose project type (I choose angel because it is the only back-end that has graphql ready

Basic (Minimal starting point for Angel 2.x - A simple server with only a few additional packages.)  
ORM (A starting point for applications that use Angel's ORM.)  
* GraphQL (A starting point for GraphQL API servers.)
Shared (Holds common models and files shared across multiple Dart projects.)  
Shared (ORM) (Holds common models and files shared across multiple Dart projects.)  

4:Angel creates a dockerfile for you change the file as below: My experience , google cloud run only allowed me to run the app on 8080 port and server set to 0.0.0.0 default options did not work. So this step is **crucial.**

FROM google/dart:latest
COPY ./ ./
# Install dependencies, pre-build
# RUN pub get
# RUN pub run build_runner build
# Set environment, start server
USER 0:0
WORKDIR /app_name
ADD pubspec.* /app_name/
RUN pub get --no-precompile
ADD . /app_name/
RUN pub get --offline --no-precompile
ENV ANGEL_ENV=production
EXPOSE 8080
CMD ["dart", "bin/prod.dart","--address","0.0.0.0","--port","8080"]
5:Create a docker image on the current directory as:
docker build .
6:Once image is built You will get a result like this Succesfully built e076b147fa81
7:Test your image on your local machine by: 
➜  app_name docker run -p 8080:8080 -it e076b147fa81
You basically forward your port 8080
8: you can visit localhost:8080  runnning your angel app on docker image
9: Submit your docker image to google cloud by:
gcloud builds submit --tag gcr.io/<project-id>/angel
10: Run your docker image on google cloud by:
gcloud beta run deploy service_name --image=gcr.io<project_id>/angel --memory 2G 

It took me a while to figure out whole stuff, but I think it is worth for having out of the box graphql support. Thanks @thosakwe for developing a great framework.

**Comment by thosakwe** [comment]
Glad you got it figured out!

**Comment by bettdouglas** [comment]
@arrrrny building the docker image using `FROM google/dart:latest` enforces that you have to use -it to enable communication to/out of the container. 
If you want to just expose the port and it works without making it interactive i.e -it use 
`FROM google/dart-runtime`

**Comment by Dokotela** [comment]
I've been working on an Immunization forecast engine using Dart, and I'm trying to setup Angel as the backend and also use Docker. My logic still needs some work, but I have been able to setup the docker container.

I used [these instructions](https://hub.docker.com/r/google/dart-runtime-base), 

One of the keys is I had to setup the folder structure a little differently than I had set it up (note, my app/project name is FhirVCA, and my local package I'm using is called fhir).

- FhirVCA
- Dockerfile
  - app
    - bin
      - server.dart
    - pubspec.yaml
  - pkg
    - fhir

And then my Dockerfile looks like this:
```
FROM google/dart-runtime-base

WORKDIR /FhirVCA/app

# Add the pubspec.yaml files for each local package.
ADD pkg/fhir/pubspec.yaml /FhirVCA/pkg/fhir/

# Template for adding the application and local packages.
ADD app/pubspec.* /FhirVCA/app/
RUN pub get
ADD . /FhirVCA
RUN pub get --offline
```
Then I was able to run:
```
$ docker build -t my/app .
$ docker run -d -p 3000:3000 my/app
```
And it works. Hope that helps anyone else trying to do this. Tobe, Angel is amazing, and so easy to use (I'm new to backends, and the fact that I could get it running at all is a testament to the incredible server package you've developed).
