### ISSUE TITLE
Are there any performance tests: Angel vs Nginx/PHP vs Node.js?

### ISSUE THREAD

**Issue by ProgrammingLife** [angel-dart/angel#126]
Are there any performance tests: Angel vs Nginx/PHP vs Node.js? How faster Angel than others or which one is slower?
Maybe Angel + dart2native improves performance?

**Comment by virgiltu** [comment]
This question does not make any sense. You are trying to benchmark Angel a framework with a programming language like Node and PHP.   Angel is framework like Laravel for PHP and Express for Node. What you need to search for on google is Dart VS Node VS PHP . Hopes this makes sense.

**Comment by virgiltu** [comment]
Just to maybe try and answer your question. The question is not really what language is faster but what uses more resources and what language can serve more requests per second. Also to remember that Dart and Node are async where PHP is not.  In other words PHP is ok for a blog that serves a few hundred clients per day but as you get more users you will be paying a lot of money for servers. In the same comparison Node and Dart will server more requests on the same amount of server. OK so enough on that. Here is another reason to consider Dart, Angel and Flutter. If you are looking to make an app that works as a website, back end, app for IOS and Android. You will only use one language. Other wise you will use PHP or Node for the server side and front end, Xcode for Iso and what ever the hell android uses now days. Also to keep in mind that Google will be replacing Android with Fuchsia in the near future that is built around Dart and Flutter so future proof all the way.  Everything also depends of how efficient you write your code,  what database you end up using and so on. This is why a question like how fast does not really matter.  Hope this gave the answer you were looking for.

**Comment by thosakwe** [comment]
A better benchmark would be a comparison between, say, Angel and Laravel, like @virgiltu mentioned. There are also the TechEmpower benchmarks, but the Angel tests are broken, and frankly their environment is almost impossible to reproduce, so I haven't been able to fix them yet, so the numbers for Angel are inaccurate.

As of the most recent benchmarks I've seen, Node.js can get higher throughput than the Dart VM, but Dart should be more than fast enough for most applications. 

Angel should be used with a reverse proxy in front of it, like `nginx`.

Also, I don't have any `dart2native` benchmarks, but for long-running servers, it's better to go with JIT, as the continuous optimizations can yield better performance in the long run. AOT for a server app is better suited for something like Firebase cloud functions.

I'm going to close this, as it's not really an "issue" in the sense of a bug report.

For further questions, it's better to ask in the chat: https://gitter.im/angel_dart/discussion

Also, see the docs site: https://docs.angel-dart.dev

**Comment by ansarizafar** [comment]
Here is a relevant discussion https://github.com/dart-lang/sdk/issues/39507 on Dart performance on the server. 

I also wanted to use Dart on the server but Dart is slower on the server and consume too much CPU. But the main reason why Dart is not suitable for server applications is lack of interest from Google to optimize Dart for Server use cases, They use Go internally for server applications. Google's aim for Dart is to make it client optimized as mentioned on the Dart website.
