### ISSUE TITLE
Better Deploy Example

### ISSUE THREAD

**Issue by mboeddeker** [angel-dart/angel#127]
Is it possible, that we can get a better deploy example ? So right now, I can't use the docker file, or I can't call my app on the localhost path. Please, an update for that topic

**Comment by thosakwe** [comment]
What specifically do you mean by "I can't use the docker file"? Are you getting errors? If so, paste them here. That being said, I don't use Docker, and that file is mostly there just to get you started.

And why can't you call the app on localhost?

Anyways, if you're deploying on Linux, the process is mostly the same as for Node.js: install Dart and nginx, setup a systemd run-forever daemon, and use nginx for SSL/reverse proxy.

I wrote this article: https://thosakwe.com/deploying-dart-apps-to-linux/

Deployment is such a general topic, though, so I don't think it would ever be possible to come with examples that fit everybody's needs. In general, you should be fine with the above article, unless you specifically *need* Docker.

**Comment by mboeddeker** [comment]
So i tried a lot of ways, and to run Angel in a docker container isn't possible right now. 

So that's my docker file:

`FROM google/dart:latest

COPY ./ ./

# Install dependencies, pre-build
RUN pub get

# Optionally build generaed sources.
# RUN pub run build_runner build

# Set environment, start server
EXPOSE 3000
CMD ["dart", "bin/main.dart"]`

Thats my docker run command:

`docker run --name podcast_api -p 3000:3000 appgewaltig/podcast_api`

Eyerytime the same, I can't connect to the container. First I thought, this is a docker problem, but then I tested it with an simple nginx alpine container, and everything is fine.

**Comment by thosakwe** [comment]
I highly doubt that running Angel in a Docker container is impossible. Running it is as simple as running the `dart` executable.

Can you paste whatever output you get here? Otherwise, I have no idea what could be going on.

That being said, there is no `bin/main.dart` file, so I can't imagine that would lead to success. So try changing that path to something else, like `bin/dev.dart`, or `bin/prod.dart`.
