### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by j209** [angel-dart/angel#128]
Hi 
When we will have the first release?

**Comment by thosakwe** [comment]
I'm confused here - there have already been dozens of versions of `package:angel_framework`, as well as the other packages.

**Comment by j209** [comment]
![Untitled](https://user-images.githubusercontent.com/18129232/73438286-0ac92880-4363-11ea-82d5-fde557510310.png)

**Comment by thosakwe** [comment]
As you can see in several places, this repo is a project boilerplate, and not the framework itself. The initial release was in 2016.

The individual source packages are in other angel-dart/* repos, like angel-dart/framework.
