### ISSUE TITLE
Q: How to write logging middleware?

### ISSUE THREAD

**Issue by nlfiedler** [angel-dart/angel#239]
I'm looking for something akin to `logRequests()` in the `shelf` package. I added a `fallback` handler but `print()` in that handler seems to be squelched. Any suggestions for how to achieve some basic request logging in Angel? Like `morgan` for express, but much simpler is fine.

**Comment by thosakwe** [comment]
The `Angel` class has a `logger` property (which points to `Logger` class from `package:logging`).

Have you seen any of the examples?

**Comment by thosakwe** [comment]
https://github.com/angel-dart/angel/blob/master/packages/framework/example/main.dart

**Comment by nlfiedler** [comment]
Does that log requests? Looks like it is only for diagnostics? Yes, I've looked at the examples. It seems that I can set the status, but throwing an exception or printing has no effect.

**Comment by thosakwe** [comment]
Yes, it will log requests, as well as exceptions. Requests are also run in a `Zone` where `print` is forwarded to the logger.

Make sure that whatever logging handler you use is also printing the associated error/stackTrace from a `LogRecord`.

**Comment by thosakwe** [comment]
The `pretty_logging` package is probably your best bet for a log handler that "just works" with colors and such out of the box.

**Comment by thosakwe** [comment]
Also, feel free to join the chat. My responses are a bit spread out, because I'm on the phone.

Unfortunately, `angel init` will not work for some time, as this repo is still in the process of becoming a monorepo, but to get a base project without too much work, clone any of the branches of `angel-dart/boilerplates`.

**Comment by nlfiedler** [comment]
Thank you for all of your help. It was difficult to know what was significant in the examples, so knowing all of the pieces that needed to be put together was hard for me. The doc comment for the logger property suggested it was only for diagnostics, and a cursory look at that one source file indicated as much. With your help, it's all working as hoped.

I'll definitely keep the chat in mind for the future. Thanks again.
