### ISSUE TITLE
Invalid check for nullability

### ISSUE THREAD

**Issue by filipproch** [angel-dart/angel#242]
Hi, using the latest version (2.0.0-beta) of `graphql_server`, upon submitting a mutation with missing variable, instead of properly answering - the server throws the null pointer exception.

I think I traced it to this line and the following null check.

https://github.com/angel-dart/angel/blob/0c30f2d0359e2a7e8c59946e7c0f53a4b3cb4d2e/packages/graphql/graphql_server/lib/graphql_server.dart#L159

It should actually be
`variableDefinition.defaultValue.value` (now its just `variableDefinition.defaultValue`)

The exception mentioned is
```
Tried calling: accept<Object>(Instance of 'GraphQLValueComputer')
[INFO] guides_backend: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      GraphQL.computeValue (package:graphql_server/graphql_server.dart:60:12)
#2      GraphQL.coerceVariableValues (package:graphql_server/graphql_server.dart:170:41)
#3      GraphQL.executeRequest (package:graphql_server/graphql_server.dart:127:33)
#4      GraphQL.parseAndExecute (package:graphql_server/graphql_server.dart:111:12)
#5      graphQLHttp.<anonymous closure>.executeMap (package:angel_graphql/src/graphql_http.dart:58:54)
```

**Comment by thosakwe** [comment]
Thanks for pointing this out - the new version changes a lot, because now it's using an entirely different parser/AST library.

Would you be interested in sending a pull request to fix this?

**Comment by filipproch** [comment]
Sure

**Comment by filipproch** [comment]
@thosakwe just don't very understand where is the `2.0.0-beta` source code, is it the `master` branch (in pubspec.yaml I see 1.1.0) ?
