### ISSUE TITLE
Any plans on conditions support for fetching relations

### ISSUE THREAD

**Issue by tabula-rasa** [angel-dart/angel#243]
That would be awesome along with selective relation loading.

**Comment by thosakwe** [comment]
Can you possibly give more details on what you'd like to see? In the beta ORM version, for a class `_A` related to class `_B`, `AQuery` has a `BQuery b` field that allows you to apply additional filters to related objects.

**Comment by tabula-rasa** [comment]
Yes, that is what I exactly need - to set filters on BQuery.
