### ISSUE TITLE
res.download file type error

### ISSUE THREAD

**Issue by massimoliani** [angel-dart/angel#246]
Sorry to disturb you.

I'm trying to make to return a file from a firabase storage using a angel.get on a pseudo folder that redirect to firebase storage using user authentication and applying a policy.

I found the download function of response context but I'm having a trouble:
type '_File' is not a subtype of type 'File'

here is the piece of code:
          var fileName = p.relative(path, from: "/gs");
          ui.ok("gs-> user uid:$uid request:$fileName");

          var file = File("lib/public/img/berlin.png");
          //print("${await file.length()}");
          return (res.download(file));
p. is the path package to extract the relative file path, here I'm just sending a local file, the file is opend correctly and the file.length is correct.

My dart version Dart VM version: 2.8.0-dev.0.0.flutter-395daaa3ec (Thu Jan 9 18:33:56 2020 +0000) on "windows_x64"

Here the pubspec.lock of angel packages:
  angel_auth:
    dependency: transitive
    description:
      name: angel_auth
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5+1"
  angel_client:
    dependency: transitive
    description:
      name: angel_client
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  angel_container:
    dependency: transitive
    description:
      name: angel_container
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  angel_framework:
    dependency: "direct main"
    description:
      name: angel_framework
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  angel_http_exception:
    dependency: transitive
    description:
      name: angel_http_exception
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  angel_jael:
    dependency: "direct main"
    description:
      name: angel_jael
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  angel_model:
    dependency: transitive
    description:
      name: angel_model
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  angel_route:
    dependency: transitive
    description:
      name: angel_route
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0+1"
  angel_static:
    dependency: "direct main"
    description:
      name: angel_static
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3+2"
  angel_websocket:
    dependency: "direct main"
    description:
      name: angel_websocket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"

Thank you for your help.

**Comment by thosakwe** [comment]
Angel uses the `File` class from `package:file`, not `dart:io` (for reasons of plugging/mocking/testing). I would try importing `package:file/local.dart` and using `LocalFileSystem().file(...)`, instead of the `File` constructor.

That's interesting, though - did the Dart analyzer not detect the error ahead of time?

**Comment by massimoliani** [comment]
No the error isn't detected in the editor. Only at runtime.
I'll try the package:file.

Thanks so much.
