### ISSUE TITLE
RangerError: Invalid value: Not in range 0..1114111 Dart VM version: 2.8.4

### ISSUE THREAD

**Issue by insinfo** [angel-dart/angel#267]
This error is in the postgres package below 2.1.1, please update the dependencies for postgres 2.1.1

https://github.com/stablekernel/postgresql-dart/issues/119

the error can be seen in this video tutorial that I recorded at 1:20:08, I had to revert to dart 2.7 so that dart 2.7 has a bug in dart: html in the form action in dart2js

https://www.youtube.com/watch?v=ZtxJhfseR4w

please update the postgres dependency

Error: Invalid value: Not in range 0..1114111, inclusive: -1 #0 StringB
uffer.writeCharCode (dart:core-patch/string_buffer_patch.dart:76:9)
PostgreSQLFormat.substitute (package:postgres/src/substituter.dart:83:29

Dart VM version: 2.8.4 (Thu Mar 26 13:15:18 2020 +0000) on "windows_x64"

Temporary correction line 66
while (iterator.current != null && iterator.current != -1) {

Source Code (FrontEnd AngularDart)
https://github.com/insinfo/crus_angular

Source Code (BackEnd Angel)
https://github.com/insinfo/crud_angel

**Comment by thiagosantoscunha** [comment]
I am having the same error presented in the previous comment.

**Comment by luX0r-reload** [comment]
In pubspec.yaml add this lines:

dependency_overrides:
  postgres: 2.1.1
