### ISSUE TITLE
It's project dead?

### ISSUE THREAD

**Issue by luX0r-reload** [angel-dart/angel#268]
Hi! I'm developing a backend with Angel but I noticed that there have been no updates for more than a month (and unanswered questions too). It's project dead?

Thanks

**Comment by insinfo** [comment]
@luX0r-reload 
I have also made several applications with Angel, and I depend a lot on this framework, I hope he doesn’t die because if I don’t have to migrate through Aqueduct or make a fork and keep this fork

**Comment by luX0r-reload** [comment]
I started migrating to Aqueduct for a new application and test it. With Angel I had implemented the authentication system with MySQL but with Aqueduct I think will have to use his Postgres ORM.

**Comment by insinfo** [comment]
@luX0r-reload
I implemented a package called fluent_query_builder, to access the database fluently, currently supports MySQL and PostgreSQL, I am using it in production with Angel and Aqueduct, if you want to use it.

https://pub.dev/packages/fluent_query_builder

**Comment by luX0r-reload** [comment]
@insinfo
Nice one! Thanks for suggest.

**Comment by pycebs** [comment]
Yes, he commented on Reddit that he will no longer work on Angel.

**Comment by sandrobilbeisi** [comment]
where on Reddit did he write that ?

**Comment by zimitz** [comment]
> where on Reddit did he write that ?

https://www.reddit.com/r/dartlang/comments/h0z413/looks_like_the_angel_webbackend_framework_wont_be/ftpaxmo/
