### ISSUE TITLE
ContentType crash

### ISSUE THREAD

**Issue by piecubed** [angel-dart/angel#269]
Stack: 
```
Error on line 1, column 16: Invalid media type: expected "/".
  ╷
1 │ applicationjson
  │                ^
  ╵
#0      wrapFormatException (package:http_parser/src/utils.dart:15:5)
#1      new MediaType.parse (package:http_parser/src/media_type.dart:46:7)
#2      HttpRequestContext.from (package:angel_framework/src/http/http_request_context.dart:92:21)
#3      AngelHttp.createRequestContext (package:angel_framework/src/http/angel_http.dart:90:31)
#4      Driver.handleRawRequest (package:angel_framework/src/core/driver.dart:94:12)
#5      Driver.startServer.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:angel_framework/src/core/driver.dart:50:20)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#8      _IterablePendingEvents.handleNext (dart:async/stream_impl.dart:540:18)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#12     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
If you send a badly formatted ContentType header, angel will crash fatally.  Can it be default behavior to send a 415 error when this happens?

**Comment by piecubed** [comment]
#270

**Comment by thosakwe** [comment]
1. This project is going to be deprecated soon. I will soon update the messaging to reflect on this.
2. I don't think that status 415 is really the right response code here; it should be a 400, as the user sent a bad request.

**Comment by luX0r-reload** [comment]
>     1. This project is going to be deprecated soon. I will soon update the messaging to reflect on this.
> 
>     
I'm really sorry. You did a great job with Angel and I like it very much. I'm Sad, cause I will have to migrate my back end to Aqueduct... but this is! Many thanks.

**Comment by insinfo** [comment]
@thosakwe
Why will this project be discontinued?

**Comment by thosakwe** [comment]
@insinfo https://www.reddit.com/r/dartlang/comments/h0z413/looks_like_the_angel_webbackend_framework_wont_be/ftpaxmo/?context=3

**Comment by insinfo** [comment]
@thosakwe 

I just read your post and I understand your arguments, if you don't mind, I would like to keep maintaining this project I don't have much time where I work, but as I am using Angel in the company where I work I would like to keep working doing bug keeping and maybe minor updates.

**Comment by thosakwe** [comment]
I don't have a problem with transferring ownership. I don't know, however, how much time I will have over the course of the next few weeks to devote to even that. So you may have to wait some time (or fork the project entirely).

**Comment by insinfo** [comment]
> So you may have to wait some time

No problem, I can wait until you have time. The problems I was having with Angel I already managed to solve in a way that suits me at the moment.

I have already solved these problems.
https://github.com/angel-dart/angel/issues/267
https://github.com/angel-dart/angel/issues/269

```yaml
#this about writing dependencies is to solve a bug in the postgres driver
#which prevents it from working with dart 2.8.4 and a bug with form data
#with UTF8 data (accented characters)
dependency_overrides:
  postgres: ^2.1.1
  http_server:
    git:
      url: https://github.com/dart-lang/http_server.git
      ref: df31d20

```
