### ISSUE TITLE
Analyzer package install error

### ISSUE THREAD

**Issue by rdnobrega** [angel-dart/angel#280]
Hi, upon using the newest Dart SDK (2.10.5), I tried to install angel_cli (pub global activate angel_cli), but it couldn't precompile, throwing the following error: "file '<analyzer pub cache folder>/lib/analyzer.dart' not found.".

As it turns out, newer versions of the analyzer package really does not come with this file. So, I manually opened pubspec.yaml from angel_cli package and downgraded the analyzer package version to 0.36.0 (as of today, current version of this package is 0.41.2).

This change allowed angel_cli to be activated correctly. However, I'm still not sure if this is a bug on the analyzer package or on angel_cli. As the latest stable version for this to work is from 2019, my guess is that angel_cli is not being updated anymore?

**Comment by dukefirehawk** [comment]
I've create a fork at https://github.com/dukefirehawk/angel that works with SDK 2.10.5 and 2.12.1. Not NNBD yet.
