### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by CodeDoctorDE** [angel-dart/angel#281]
It would be cool if you migrate your library to support null safety.
See the docs [here](https://dart.dev/null-safety)

**Comment by kalmigs** [comment]
someone is actively migrating it to null-safety here: https://github.com/dukefirehawk/angel/wiki/Change-Log

**Comment by luffyjie** [comment]
+1 salute!  I currently looking for dart backend framework to start develop mobile application. I find aqueduct is top maintain too sad for dart backend community!
 Hope support null safety! 💗

**Comment by Wissperwind** [comment]
Try Jaguar.

**Comment by kalmigs** [comment]
> +1 salute! I currently looking for dart backend framework to start develop mobile application. I find aqueduct is stop maintain too sad for dart backend community!
> Hope support null safety! heartpulse

Yeah aqueduct is now archived but there is a community fork that I think is actively maintained: https://github.com/conduit-dart/conduit/

**Comment by CodeDoctorDE** [comment]
https://github.com/aldrinsartfactory/liquidart here is the active fork!

**Comment by kalmigs** [comment]
> https://github.com/aldrinsartfactory/liquidart here is the active fork!

Thanks for this! didn't know there was another group maintaining an active fork of aqueduct
