### ISSUE TITLE
The example in the Error handling wiki

### ISSUE THREAD

**Issue by fredtma** [angel-dart/angel#33]
>  final errors = new ErrorHandler({
>   404: (req, res) async => render404Page(),
>   403: (req, res) async => renderForbidden(),
>   500: (req, res) async => renderGenericErrorPage()
> });

Should be 
>  final errors = new ErrorHandler(handlers: {
>   404: (req, res) async => render404Page(),
>   403: (req, res) async => renderForbidden(),
>   500: (req, res) async => renderGenericErrorPage()
> });

**Comment by thosakwe** [comment]
Thanks, will fix ASAP.
