### ISSUE TITLE
Virtual Directory Issue

### ISSUE THREAD

**Issue by fredtma** [angel-dart/angel#40]
Maybe I am doing this wrong, I want to be redirected to the swagger-ui directory with the following code.

`await app.configure(new VirtualDirectory(source: new Directory('node_modules/swagger-ui-dist/'), publicPath: 'swagger/'));`

However, I see that on line 89 in file `virtual_directory.dart`  the variable `_prefix` is assigned the value of the `publicPath` variable with the slash removed.

`_prefix = publicPath.replaceAll(_straySlashes, '');`

`_prefix` is then used to replace the path with an empty string on line 179.

`path = path.replaceAll(new RegExp('^' + _pathify(_prefix)), '');`

`path` is later used to resolve to the `source` directory on line 184

Problem comes when, If I have path e.g. `/swagger/index.html`
The following will happen.

189: `path = '/swagger/index.html'.replaceAll(new RegExp('^' + _pathify('swagger')), '');`
//path = '/index.html'
184 var absolute = source.absolute.uri.resolve(path).toFilePath();
//absolute = '/index.html'

The forward slash in the path resolves it to the /root directory.
Adding
`path = path.replaceAll(_straySlashes, '');`
solve this for me as a temp solution

**Comment by thosakwe** [comment]
Also was able to patch this up. Should work now!
