### ISSUE TITLE
Virtual Directory not working without forward slash `/`

### ISSUE THREAD

**Issue by fredtma** [angel-dart/angel#41]
When creating a VR Dir with

`await app.configure(new VirtualDirectory(source: new Directory('node_modules/swagger-ui-dist/'), publicPath: 'swagger',));`

If you go to `http://localhost:3000/swagger/` this will work because there is a root `/`
but `http://localhost:3000/swagger` without the `/` won't work.
Also when you do a trace in the code, you will notice that if you make a request for a file named the same as the publicPath, that file will be replaced in the file `virtual_directory.dart` line 179

@ `path = path.replaceAll(new RegExp('^' + _pathify(_prefix)), '');`

if `path = 'swagger-ui.css'` it will result to `-ui.css`
This only happens when the request does not have '/'

**Comment by thosakwe** [comment]
Hi, thanks for filing these issues! Hopefully they'll be resolved by the end of the day.

**Comment by thosakwe** [comment]
Just fixed this issue. I'll publish an update within a half hour.

**Comment by thosakwe** [comment]
Okay, just published `v1.2.3` to Pub. Thanks for your help!

https://github.com/angel-dart/static/commit/a55f97c87157a84ac3b65747cf74701408b77ca1

**Comment by fredtma** [comment]
Thanks @thosakwe .
I have a follow-up to this, it's not a bug.

Scenario is
When I use http://locahost:3000/swagger without ending with '/'
and include a reference in the index.html as 
`<link rel="stylesheet" type="text/css" href="tmp/swagger-ui.css" >`
The request sent is **tmp/swagger-ui.css**

I would like to add a middleware that will modify the **RequestContext** path that will append the Virtual Root ('swagger/') but this is a readonly. Is there away to change this (req.path)?

The midWare will be something like.

    app.before.add((RequestContext req) {
        if((req.path as String).startsWith('swagger/') == false) {
            req.path = 'swagger/' + req.path;
        }
    });

**Comment by thosakwe** [comment]
There's no way to change req.path. However, there's are a few workarounds. Give me a minute.

**Comment by thosakwe** [comment]
1. The simplest way is to call `VirtualDirectory.servePath`: 
```dart
import 'package:path/path.dart' as p;

app.before.add((req) {
  if (!req.path.startsWith('swagger'))
    return vDir.servePath(req.path);
});
```

The `VirtualDirectory` API is documented in two places:
https://pub.dartlang.org/packages/angel_static
https://www.dartdocs.org/documentation/angel_static/1.2.3/

**Comment by thosakwe** [comment]
2. The second way is a little hackier. It uses a package I wrote called `mock_request`. Essentially you create a fake HttpRequest, and then have Angel process it. Then you just send that response, and skip the rest of the response handling.
https://github.com/thosakwe/mock_request

```dart
hackyFix(RequestContext req, ResponseContext res) async {
  var rq = new MockRequest('GET', new Uri(path: '/swagger/tmp/swagger-ui.css'));
  var rs = rq.response;
  // Have Angel process the mock request.
  await app.handleRequest(rq);

  // Now, signal to Angel that the response is done, and that Angel should not try to send the response.
  // This lets us prematurely exit the request lifecycle.
  // https://github.com/angel-dart/angel/wiki/Request-Lifecycle
  res
    ..willCloseItself = true
    ..end();

  // Now we just copy to the underlying `dart:io` HttpRequest and send...
  res.io.statusCode = rs.statusCode;
  copyHeaders(rs.headers, res.io.headers);
  
  // This will copy all content, gzipped
  res.io.headers.set(HttpHeaders.CONTENT_ENCODING, 'gzip');
  await rs.transform(GZIP.encoder).pipe(res.io);
}
```

The `copyHeaders` function is exported by `package:angel_proxy`. If you're importing `angel_common`, this will already be in the global namespace.

https://www.dartdocs.org/documentation/angel_proxy/1.0.8/angel_proxy/angel_proxy-library.html
