### ISSUE TITLE
Response is not stooped on 404 

### ISSUE THREAD

**Issue by fredtma** [angel-dart/angel#42]
On an angel init project 1 (full project), if you target nonexisting resource e.g http://localhost:3000/notFound, you will get an endless pending resource.

in lib/src/routes/routes.dart if you use comment out the exception handling and use

`app.after.add((ResponseContext res) => 'Not Found');`

This will work but the current way it is setup with the default template does not work event though the error is caught.
online 28 in the file plugin.dart whether I  variable result with a bool value of false or a Map back the request does not end.

**Comment by thosakwe** [comment]
Thanks. I made a change to the way errors are handled, and I think it broke some things. Going to revert it today.

**Comment by thosakwe** [comment]
Not going to be home for a few days. For now, please downgrade to angel_framework <= 1.0.3

**Comment by thosakwe** [comment]
@fredtma I was able to find where this bug came from, and it's been fixed with this commit: https://github.com/angel-dart/framework/commit/58ec66f4543af801f3851b03a198eb062d2c3c0a

I'm aiming to publish v1.0.6 of `package:angel_framework` tonight.

**Comment by thosakwe** [comment]
Resolved!
