### ISSUE TITLE
Issues with cli tooling (win10, 64 bits)

### ISSUE THREAD

**Issue by rishavs** [angel-dart/angel#43]
Hi

I just tried Dart for the first time.
I have 2 major issues which are stopping me from even starting out;

1.  When i try `pub global activate angel_cli`, the process gets stuck at `Installed executable angel.`.
I am assuming that Angel was indeed instaled but i am not sure if any further steps were not performed.

2.  `angel init` goes into a loop and as such i am not even able to create a boilerplate project.

```
PS C:\Users\Mockingbird\DevSpace\Dart\angelu> angel init
Creating new Angel project in C:\Users\Mockingbird\DevSpace\Dart\angelu\....
[1] Yes
[2] No
Directory 'C:\Users\Mockingbird\DevSpace\Dart\angelu\.' already exists. Overwrite it? (Yes/No)y
[1] Yes
[2] No
Directory 'C:\Users\Mockingbird\DevSpace\Dart\angelu\.' already exists. Overwrite it? (Yes/No)y
[1] Yes
[2] No
Directory 'C:\Users\Mockingbird\DevSpace\Dart\angelu\.' already exists. Overwrite it? (Yes/No)y
[1] Yes
[2] No
Directory 'C:\Users\Mockingbird\DevSpace\Dart\angelu\.' already exists. Overwrite it? (Yes/No)y
[1] Yes
[2] No
Directory 'C:\Users\Mockingbird\DevSpace\Dart\angelu\.' already exists. Overwrite it? (Yes/No)y
[1] Yes
[2] No
Directory 'C:\Users\Mockingbird\DevSpace\Dart\angelu\.' already exists. Overwrite it? (Yes/No)y
[1] Yes
[2] No
Directory 'C:\Users\Mockingbird\DevSpace\Dart\angelu\.' already exists. Overwrite it? (Yes/No)
[1] Yes
[2] No
Directory 'C:\Users\Mockingbird\DevSpace\Dart\angelu\.' already exists. Overwrite it? (Yes/No)
[1] Yes
[2] No
Directory 'C:\Users\Mockingbird\DevSpace\Dart\angelu\.' already exists. Overwrite it? (Yes/No)
[1] Yes
[2] No
Directory 'C:\Users\Mockingbird\DevSpace\Dart\angelu\.' already exists. Overwrite it? (Yes/No)
[1] Yes
[2] No
```

I am on windows 10, 64 bits and have installed Angel CLI version 1.1.4.
Dart is `Dart VM version: 1.24.2 (Thu Jun 22 08:55:56 2017) on "windows_x64"`

**Comment by thosakwe** [comment]
#1 seems to not be an issue with the CLI itself.
#2 is a new issue I was unaware of, thank you. For now, pass an additional argument to the init command to create a project in a subdirectory. Ex: "angel init hello"

**Comment by thosakwe** [comment]
Actually, now that I'm reading it, #2 isn't an issue... 

If you try to initialize a project in the *current* directory, or one which already exists, the CLI will ask for confirmation so that it doesn't overwrite existing files without express consent. You need to type "1", "2", "Yes", or "No". 

In general, initializing into a subdirectory is always more straightforward.

Going to mark this as closed.

**Comment by rishavs** [comment]
Thanks. that was fast.
I tried `angel init hello` but now it is stuck at resolving dependencies.

```
Now running pub get...
Running pub at "C:/tools/dart-sdk/bin/pub.bat"...
Resolving dependencies...
```

**Comment by thosakwe** [comment]
Let it run; pub takes a bit to install the dependencies.

**Comment by rishavs** [comment]
been a long while. Anyway i can run the init command on verbose?

**Comment by thosakwe** [comment]
Any luck with `pub get`?
