### ISSUE TITLE
MimeType == null for Virtual Directory

### ISSUE THREAD

**Issue by fredtma** [angel-dart/angel#44]
I failed to do a pull request on the [Angel Static Plugin](https://github.com/angel-dart/static).
So I'll put my suggestion here.

In the file `virtual_directory.dart` line 290 about.
`lookupMimeType(file.path)` sometimes returns a mime of `null`, this in turn, causes non-critical error logs when writting the header in `dart:io` -> `http_headers.dart`

I added a default value of 'text/plain'.

    String type = lookupMimeType(file.path) ?? 'text/plain';
    _ensureContentTypeAllowed(type, req);
    res.headers[HttpHeaders.CONTENT_TYPE] = type;

    if (streamToIO == true) {
      res
        ..io.headers.set(HttpHeaders.CONTENT_TYPE, type)
        ..io.headers.set(HttpHeaders.CONTENT_ENCODING, 'gzip')
        ..end()
        ..willCloseItself = true;

      await file.openRead().transform(GZIP.encoder).pipe(res.io);
    } else {
      await res.sendFile(file);
    }

**Comment by thosakwe** [comment]
Thanks. I'll fix this up later today. Out of curiosity, which file extensions have you found that cause the MIME type lookup to return null?

**Comment by fredtma** [comment]
I am using the [swagger-ui-dist](https://github.com/swagger-api/swagger-ui)  to document the api.
This makes use of minified js & css files, which makes request to *.map files. These are not found in the 
mimeType library.

**Comment by thosakwe** [comment]
Thanks.

**Comment by thosakwe** [comment]
Note to self: only encode the file as GZIP if the client accepts it...

**Comment by thosakwe** [comment]
Okay, this should be patched up via `package:angel_static@1.2.4`.

https://github.com/angel-dart/static/blob/master/CHANGELOG.md
