### ISSUE TITLE
MIME type error

### ISSUE THREAD

**Issue by rickbsgu** [angel-dart/angel#45]
Hi -

I think this might have something to do with the latest Dartium update and the Issue #44 fix (that may need  to be re-opened.)

Fresh clone, trying to access 'localhost:3000' I get:

`Refused to execute script from 'http://localhost:3000/packages/browser/dart.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

Maybe I can disable strict MIME-type checking in the browser, but that's not a real fix.

Thoughts appreciated,
thanx,
rickb

**Comment by thosakwe** [comment]
It's nothing to do with the recent issue; this means that the response your server is sending when `packages/browser/dart.js` is requested is not a JavaScript file. I'm 99% sure that your server is rendering a 404/fallback page. And here's why...

A URL like `/packages/browser/dart.js` in the Dart world is served one of two ways:
1. `pub serve` handles this, and returns the contents of the file `lib/dart.js` in the directory where `package:browser` is found in your system's Dart cache.
2. You've run `pub build` beforehand, and it copied the file to `/build/web/packages/browser/dart.js`.

In case 1, you'll need to run `pub serve` along Angel. Also, ensure that you have a `PubServeLayer` configured, *before* any virtual directories, or fallback routes:

```dart
createServer() async {
  var app = new Angel();
  await app.configure(new PubServeLayer());
  await app.configure(new CachingVirtualDirectory());
  app.after.add(() => throw new AngelHttpException.notFound());
}
```

If you take a look at the Developer Tools, you'll see that the response to `/packages/browser/dart.js` was some sort of HTML fallback page.

You can also support pushstate routing: https://github.com/angel-example/push_state

Make sure to read the documentation about the request lifecycle; it's fundamental to using and understanding the Angel framework: https://github.com/angel-dart/angel/wiki/Request-Lifecycle

---

In case 2, ensure you have a `VirtualDirectory` or `CachingVirtualDirectory` running. It'll choose to serve from `web` or `build/web` for you by default. You can also explicitly set the source directory.

Read: https://medium.com/the-angel-framework/serving-static-files-with-the-angel-framework-2ddc7a2b84ae

**Comment by rickbsgu** [comment]
Ok, I guess I don't understand.  I haven't run `pub build`, I'm just trying to serve it in developer mode.

I'm starting the server with `dart --observe bin/server.dart` (from the project root directory).

`server.dart` includes `angel_note.dart` which contains the `createServer()` invocation, and in that function, `virtualDirectory()` is invoked (line 124).

Are you saying that I need to run `pub serve` as well as `dart --observe bin/server.dart`?  Angel is not a standalone server?

I'm plowing through the documentation & will scour the points you reference.

thanx,
rickb

**Comment by thosakwe** [comment]
Angel is indeed a standalone server; therefore, it doesn't compile your client-side Dart assets. That's the job of `pub serve`. So, you have to run `pub serve` as well as `dart --observe bin/server.dart`.

The `dart:io` library has code to spawn processes, so if you'd like, you can add code that starts `pub serve` as a child process whenever the server starts.

**Comment by thosakwe** [comment]
Since we've determined that this isn't an issue with the framework, please join the Gitter chat to discuss it with me:

https://gitter.im/angel_dart/discussion

**Comment by rickbsgu** [comment]
Oh, man -- I'm sorry.  This is for the 'Angel Angular' example.  Somehow I wound up in the Angel itself.

**Comment by thosakwe** [comment]
It's all good.
