### ISSUE TITLE
Test `isProduction` behavior in plug-in

### ISSUE THREAD

**Issue by thislooksfun** [angel-dart/angel#46]
Hello,

I'm writing a plug-in for Angel, and I have some production-only behavior that I would like to test before shipping it. Is there any way (outside of running the test twice) to test both with `isProduction` `false` and with it `true`?

Thanks,
-tlf

P.S. Sorry if I'm missing something obvious, I'm fairly new to Dart.

**Comment by thosakwe** [comment]
Sorry for the late response. There is no way to do this. This is by design.
