### ISSUE TITLE
Angel 1.0.0 -> 1.1.0 migration guide

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/angel#49]
Based on the changelog, up to `1.1.0`: https://pub.dartlang.org/packages/angel_framework/versions/1.1.1#-changelog-tab-

Main points:
* `angel_diagnostics` is deprecated - instead just pass a `Logger` and set it as `app.logger`.
* Removed `AngelFatalError`, and subsequently `fatalErrorStream`.
  * Errors are automatically create `500`. Set `app.logger` to see output.
  * `angel_errors` is no longer useful.
* Removed all `@deprecated` members.
* Removed @Hooked, beforeProcessed, and afterProcessed.
* Made injections in RequestContext private.
* Renamed properties in AngelBase to configuration.
* Added support for pattern matching and other injections via `@Parameter()`
* Officially deprecated properties in Angel.
* Fixed a bug where cached routes would not heed the request method. #173
* Reworked error handling logic; now, errors will not automatically default to sending JSON.
* Removed the onController stream from Angel.
* Controllers now longer use call, which has now been renamed to configureServer.

Aside from these points, there are several things to note.

Migration in itself will be pretty easy to achieve. Plugins and services haven't really changed, it's just the HTTP server itself.

**Comment by kingkazuma** [comment]
In 1.1.0, Removed Angel.after, before, justBeforeStart, justBeforeStop and fatalErrorStream,
What should I use instead of？

**Comment by thosakwe** [comment]
1. There is no replacement for before/after. This way, it is easier to keep track of the order request handlers run. responseFinalizers are still in place.
2. justBeforeStart, justBeforeStop => startupHooks, shutdownHooks
3. fatalErrorStream is no longer necessary; you can just set app.errorHandler. Fatal errors will be wrapped in a 500 response

**Comment by kingkazuma** [comment]
emm, So, how should i define global middleware?
Angel.use("/.*", null, (res, rep)=> ... ) ?

**Comment by thosakwe** [comment]
`app.use((req, res) => ...)`

Much cleaner in 1.1.0. 😄

**Comment by kingkazuma** [comment]
Thanks!  : )
