### ISSUE TITLE
Adding Controller

### ISSUE THREAD

**Issue by DrivEddy** [angel-dart/angel#53]
Hey, 

when I try to add an controller I get the following message. 

` can't be assigned to the parameter type '(Angel) → Future<dynamic>'. `

When I digged into the code I noticed that 

```
    if (configurer is Controller)
      _onController.add(controllers[configurer.findExpose().path] = configurer);
``` 

got removed from the the `configure` method. Are controller not supported anymore? 

Im using version 
`angel_framework: "^1.1.1"`

**Comment by thosakwe** [comment]
They are still supported, but you should use the `configureServer` method of your controller:

```dart
await app.configure(new MyController().configureServer);
```

Still working on upgrading the documentation. See #49.

**Comment by DrivEddy** [comment]
Hey @thosakwe that was super quick. Thanks a lot!!!
