### ISSUE TITLE
Error is not caught by Angel, server instance terminates

### ISSUE THREAD

**Issue by daniel-v** [angel-dart/angel#54]
Reproduction:

```dart
    app.responseFinalizers.add((req, res) {
      Stopwatch sw = req.properties['__stopwatch'];
      sw.stop();
    })
```

```
Unhandled exception:
NoSuchMethodError: The method 'stop' was called on null.
Receiver: null
Tried calling: stop()
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
```

Seems like responseFinalizers are not handled the same way as handlers.

**Comment by thosakwe** [comment]
As of `package:angel_framework@1.1.3`, requests in `AngelHttp` are handled in custom Zones, and therefore will not crash the server.

This functionality has not been ported to `AngelHttp2` yet.
