### ISSUE TITLE
A build action is attempting to operate on a package which is not the root

### ISSUE THREAD

**Issue by alaister** [angel-dart/angel#55]
I'm new to Angle and am trying to generate orm code. I'm running the command `dart tool/build.dart` which throws the error:
```
A build action is attempting to operate on a package which is not the root.
...
../../runtime/vm/dart_api_impl.cc: 1878: error: Dart_GetMainPortId expects there to be a current isolate. Did you forget to call Dart_CreateIsolate or Dart_EnterIsolate?
```

Am I doing something wrong here?

**Comment by thosakwe** [comment]
I actually don't know what the cause might be; perhaps create an issue in the `build` repository?

Also, the ORM has not yet been updated to the new `package:build`. I'm largely looking for community contribution on that, as I personally don't use PostgreSQL often, and not many Angel users have expressed interest in using it.

**Comment by alaister** [comment]
Okay no worries - I'll learn some more dart and see if I can work it out :)

**Comment by thosakwe** [comment]
Also, check out the Gitter: https://gitter.im/angel_dart/discussion
