### ISSUE TITLE
Cant install. 

### ISSUE THREAD

**Issue by virgiltu** [angel-dart/angel#60]
Any ideas on what could cause this issue? 

> Choose a project type before continuing:
[1] Basic (Minimal starting point - A simple server with only a few additional packages.)
[2] ORM (A starting point for applications that use Angel's ORM.)
Choice: 1
Cloning "Basic" boilerplate from "https://github.com/angel-dart/angel.git"...
ProcessException: The system cannot find the file specified.
  Command: git clone --depth 1 https://github.com/angel-dart/angel.git C:\Users\virgi\Desktop\app\hello
✗ Could not initialize Angel project.
Oops, something went wrong: ProcessException: The system cannot find the file specified.
Command: git clone --depth 1 https://github.com/angel-dart/angel.git C:\Users\virgi\Desktop\app\hello

**Comment by virgiltu** [comment]
Thank you Tobe. angel doctor is giving me Git not found. Reinstalled git but same issue. I will try to diagnose more. 

Also thanks for the great videos on youtube. I just started to fallow your channel an hour before I posted this.

**Comment by thosakwe** [comment]
Will do! Thanks!

**Comment by virgiltu** [comment]
More of a question request. In a meeting today a few software developers were talking about angel dart. If you had a full course on udemy a lot of these guys would be more than happy to buy it. The reason this is prefers is because most software developers can expense udemy courses. The YouTube videos are great but we would love to see more up to date stuff, and also ensure that you get reworded for the content.
