### ISSUE TITLE
Update angel_rethink to Angel 2

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/angel#71]
Again, not much to be done here: https://github.com/angel-dart/rethink

* Remove `dart2_constant`, if any.
* Import `package:angel_framework/http.dart` in example, if necessary.
* Remove any `json_god`/`dart:mirrors` (I don't think there is any anymore, regardless).

Also, the class should look like follows (basically just add the type parameters!):

```dart
class RethinkService extends Service<String, Map<String, dynamic>> {
  Future<List<Map<String, dynamic>> index([Map<String, dynamic> params]);
  Future<Map<String, dynamic> read(String id, [Map<String, dynamic> params]);
  Future<Map<String, dynamic> create(Map<String, dynamic> data, [Map<String, dynamic> params]);
  Future<Map<String, dynamic> modify(String id,Map<String, dynamic> data, [Map<String, dynamic> params]);
  Future<Map<String, dynamic> update(String id,Map<String, dynamic> data, [Map<String, dynamic> params]);
  Future<Map<String, dynamic> remove(String id, [Map<String, dynamic> params]);
}
```

**Comment by gokomer** [comment]
Hello @thosakwe. I know https://github.com/billysometimes/rethinkdb/issues/63 blocks this and you got involved with this issue but it looks like author gave up on it. So what's the game plan?

**Comment by thosakwe** [comment]
The intent is to eventually finish upgrading this, but I want to get Angel 2.0 released first. There's a significant amount that needs to be changed in the rethinkdb library to work with Dart 2. Meanwhile, Angel 2.0 is essentially done, so I don't want to delay the release any longer.

**Comment by ssummer** [comment]
Is this likely to be completed anytime soon? Would really like to try out rethinkdb with Angel 2.

**Comment by thosakwe** [comment]
No. I am planning to discontinue Angel. However, someone has offered to take over maintenance, so I guess it depends on how that goes.
