### ISSUE TITLE
Update angel_file_security to Angel 2, and roll into angel_security

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/angel#77]
No sense in having its own separate package. 

* Update deps
* Remove any dart2_constant
* Import angel_framework/http.dart where needed
* *Remove* `VirusTotalScanner` class
* Move into `package:angel_security`.

Also see #75 

https://github.com/angel-dart/file_security

**Comment by lenniezelk** [comment]
i'd like to work on this @thosakwe

**Comment by thosakwe** [comment]
@lenniezelk Thanks! At this point, though, the functionality from `file_security` is actually present in the alpha version of `angel_validate`, which provides `Field` classes that can be used individually to read sanitized data, or combined into a `Form`.

https://pub.dev/documentation/angel_validate/3.0.0-alpha/without_matcher/FileField-class.html
