### ISSUE TITLE
Deprecate (or update?) angel_firebase

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/angel#86]
Originally, the goal was to allow people to gradually begin a switch to Angel, without getting entirely rid of their Firebase. It would also mean being able to use Firebase as your database, while still using Angel as your API - a nice combo if your situation requires it.

The thing is, there is not much functionality in `package:firebase/firebase_io.dart` *yet*, so it would require a bit of upstream change.

If people are really passionate about mixing Firebase and Angel, though, I'll join you in contributing io functionality to upstream.

https://github.com/angel-dart/firebase

**Comment by thedejifab** [comment]
Update please

**Comment by thosakwe** [comment]
Not 100% sure if it's feasible - there's not much server-side support for Firebase within Dart.

**Comment by thedejifab** [comment]
Dart and this server-side support ish. Well, I hope its feasible

**Comment by thosakwe** [comment]
I intend to deprecate `package:angel_firebase` at this point.
