### ISSUE TITLE
angel_angular

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/angel#87]
Not so sure about the vision of this project is anymore, at this point. I haven't used Angular in some time, but I'll need to revisit it at some point to update this.

**Comment by rakeshlanjewarwork** [comment]
Hey Dev,
             Just asking generally, why you need to develop this package ?
             Because there is angulardart package already available

**Comment by thosakwe** [comment]
Well, the entire point is to provide utilities to make it easier/faster to develop an Angular frontend for an Angel backend.

That being said, I haven't seen any specific interest in something like this, and it's already easy enough to use Angular with Angel without any special tools. So I'm going to go ahead and close this, as it's been open over a year.
