### ISSUE TITLE
Deprecate angel_toggle?

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/angel#89]
While the premise was interesting, it's not such a great practice to not test against the same store you'll be using in production.

https://github.com/angel-dart/toggle

**Comment by Immortalin** [comment]
Makes development faster though. Change toggle backend to SQLite in-memory mode maybe?

**Comment by thosakwe** [comment]
Well, either way, it’d still be a `Service<String, Map<String, dynamic>>`, so the current in-memory service should be more than fine.

I think I’ll re-release this package right after Angel 2.0 comes out (hopefully next week), and just be very sure that users are aware of the potential implications of developing against a different database from production.

One thing that’s about to change is that Angel.isProduction will be deprecated in favor of the new `AngelEnv` class, which is pluggable, and also handles options other than dev/prod, i.e. staging, etc.
