### ISSUE TITLE
Docker file won't build

### ISSUE THREAD

**Issue by clarkezone** [angel-dart/angel#97]
Jamess-MBP-2018:angel jamesclarke$ docker build . -t myangel
flock                    od                  sha384sum         yes                                   │Sending build context to Docker daemon  297.5kB
fmt                      oldfind             sha512sum         zdump                                 │Step 1/24 : FROM ubuntu:16.04
fold                     openssl             shasum            zipdetails                            │16.04: Pulling from library/ubuntu
root@52df54ca3d89:/Source/Temp# /usr/bin/d                                                           │7b8b6451c85f: Pull complete 
dart                     debconf-set-selections   dirname                  dpkg-split                │ab4d1096d9ba: Pull complete 
debconf                  debconf-show             dpkg                     dpkg-statoverride         │e6797d1788ac: Pull complete 
debconf-apt-progress     delpart                  dpkg-deb                 dpkg-trigger              │e25c5c290bde: Pull complete 
debconf-communicate      diff                     dpkg-divert              du                        │Digest: sha256:e547ecaba7d078800c358082088e6cc710c3affd1b975601792ec701c80cdd39
debconf-copydb           diff3                    dpkg-maintscript-helper                            │Status: Downloaded newer image for ubuntu:16.04
debconf-escape           dircolors                dpkg-query                                         │ ---> a51debf7e1eb
root@52df54ca3d89:/Source/Temp# /usr/bin/d                                                           │Step 2/24 : MAINTAINER Tobe O <thosakwe@gmail.com>
dart                     debconf-set-selections   dirname                  dpkg-split                │ ---> Running in d3d6b8e75fec
debconf                  debconf-show             dpkg                     dpkg-statoverride         │Removing intermediate container d3d6b8e75fec
debconf-apt-progress     delpart                  dpkg-deb                 dpkg-trigger              │ ---> 017f0275d5b1
debconf-communicate      diff                     dpkg-divert              du                        │Step 3/24 : RUN sudo apt-get update
debconf-copydb           diff3                    dpkg-maintscript-helper                            │ ---> Running in 7aa68790a969
debconf-escape           dircolors                dpkg-query                                         │/bin/sh: 1: sudo: not found
root@52df54ca3d89:/Source/Temp# ls /usr/bin/dart/                                                    │The command '/bin/sh -c sudo apt-get update' returned a non-zero code: 127

**Comment by thosakwe** [comment]
I don't use Docker; the file there is mainly for reference. Feel free to send in a PR.

This one I wrote works though:
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Dart/angel/angel.dockerfile

**Comment by thosakwe** [comment]
I'm closing this, but going to update the Dockerfile.

**Comment by thosakwe** [comment]
Now fixed...
